"""
Report Generator Module
Generates structured security reports in JSON and HTML formats.
"""
import json
from pathlib import Path
from datetime import datetime
from config import REPORT_DIR
from utils.logger import get_logger

logger = get_logger("ReportGenerator")


class ReportGenerator:
    def __init__(self, app_name: str, platform: str):
        self.app_name = app_name
        self.platform = platform
        self.timestamp = datetime.now().isoformat()

    def generate_json(self, analysis_results: dict) -> Path:
        report = {
            "report_metadata": {
                "application_name": self.app_name,
                "platform": self.platform,
                "analysis_timestamp": self.timestamp,
                "agent": "Mobile Security Agent v1.0",
            },
            **analysis_results,
        }
        filename = f"report_{self.app_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        path = REPORT_DIR / filename
        path.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
        logger.info(f"JSON report saved: {path}")
        return path

    def generate_html(self, analysis_results: dict) -> Path:
        risk = analysis_results.get("risk_assessment", {})
        findings = risk.get("findings", [])
        summary = risk.get("risk_summary", {})
        overall = risk.get("overall_risk", "info")

        severity_colors = {"critical": "#dc2626", "high": "#ea580c", "medium": "#d97706", "low": "#2563eb", "info": "#6b7280"}

        rows = ""
        for i, f in enumerate(findings, 1):
            sev = f.get("severity", "info")
            color = severity_colors.get(sev, "#6b7280")
            rows += f"""<tr>
              <td>{i}</td>
              <td>{f.get('title','')}</td>
              <td><span class="badge" style="background:{color}">{sev.upper()}</span></td>
              <td>{f.get('cvss_score',0)}</td>
              <td>{f.get('description','')}</td>
              <td>{f.get('cwe','')}</td>
              <td>{f.get('owasp','')}</td>
            </tr>"""

        html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Security Report - {self.app_name}</title>
<style>
  *{{margin:0;padding:0;box-sizing:border-box}}
  body{{font-family:'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0;padding:2rem}}
  .header{{text-align:center;margin-bottom:2rem}}
  .header h1{{font-size:2rem;background:linear-gradient(135deg,#06b6d4,#8b5cf6);-webkit-background-clip:text;-webkit-text-fill-color:transparent}}
  .summary{{display:flex;gap:1rem;justify-content:center;margin:2rem 0;flex-wrap:wrap}}
  .stat{{background:#1e293b;border-radius:12px;padding:1.5rem 2rem;text-align:center;min-width:120px}}
  .stat .num{{font-size:2rem;font-weight:700}}
  .stat .label{{font-size:.85rem;opacity:.7}}
  table{{width:100%;border-collapse:collapse;background:#1e293b;border-radius:12px;overflow:hidden;margin-top:1rem}}
  th{{background:#334155;padding:12px;text-align:left;font-size:.85rem;text-transform:uppercase;letter-spacing:.05em}}
  td{{padding:12px;border-bottom:1px solid #334155;font-size:.9rem}}
  .badge{{padding:4px 10px;border-radius:999px;color:#fff;font-size:.75rem;font-weight:600;text-transform:uppercase}}
</style></head><body>
<div class="header">
  <h1>🛡️ Mobile Security Report</h1>
  <p>{self.app_name} | {self.platform.upper()} | {self.timestamp}</p>
</div>
<div class="summary">
  <div class="stat"><div class="num" style="color:#dc2626">{summary.get('critical',0)}</div><div class="label">Critical</div></div>
  <div class="stat"><div class="num" style="color:#ea580c">{summary.get('high',0)}</div><div class="label">High</div></div>
  <div class="stat"><div class="num" style="color:#d97706">{summary.get('medium',0)}</div><div class="label">Medium</div></div>
  <div class="stat"><div class="num" style="color:#2563eb">{summary.get('low',0)}</div><div class="label">Low</div></div>
  <div class="stat"><div class="num" style="color:#6b7280">{summary.get('info',0)}</div><div class="label">Info</div></div>
</div>
<h2 style="margin:1.5rem 0 .5rem">Overall Risk: <span style="color:{severity_colors.get(overall,'#6b7280')}">{overall.upper()}</span></h2>
<table><thead><tr><th>#</th><th>Title</th><th>Severity</th><th>CVSS</th><th>Description</th><th>CWE</th><th>OWASP</th></tr></thead>
<tbody>{rows}</tbody></table>
<p style="text-align:center;margin-top:2rem;opacity:.5">Generated by Mobile Security Agent v1.0</p>
</body></html>"""

        filename = f"report_{self.app_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        path = REPORT_DIR / filename
        path.write_text(html, encoding="utf-8")
        logger.info(f"HTML report saved: {path}")
        return path
